version: '3'

services:
  jupyterlab:
    container_name: jupyterlab
    build: .
    command: jupyter lab --allow-root --ip="0.0.0.0"
    volumes:
      - .aws:/root/.aws
      - ./:/code
    ports:
      - "8888:8888"

volumes:
  data01:
    driver: local
